import esbuild from "esbuild";
import process from "process";
import { polyfillNode } from "esbuild-plugin-polyfill-node";

// Node.js built-in modules to exclude from bundling
const nodeBuiltins = [
	"assert", "async_hooks", "buffer", "child_process", "cluster", "console",
	"constants", "crypto", "dgram", "diagnostics_channel", "dns", "dns/promises",
	"domain", "events", "fs", "fs/promises", "http", "http2", "https", "inspector",
	"inspector/promises", "module", "net", "os", "path", "path/posix", "path/win32",
	"perf_hooks", "process", "punycode", "querystring", "readline", "repl",
	"stream", "stream/consumers", "stream/promises", "stream/web", "string_decoder",
	"sys", "timers", "timers/promises", "tls", "trace_events", "tty", "url",
	"util", "util/types", "v8", "vm", "wasi", "worker_threads", "zlib"
];

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
	],
	format: "cjs",
	platform: "browser",
	mainFields: ["browser", "module", "main"],
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	alias: {
		"fs-extra": "./stub.js",
		"graceful-fs": "./stub.js"
	},
	plugins: [
		polyfillNode({
			polyfills: {
				fs: true,
				crypto: true,
				os: true,
				path: true,
				stream: true,
				events: true,
				buffer: true,
			}
		}),
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}